using Blazix.BaseUI.Parity.Tests.Components;
using Microsoft.Extensions.FileProviders;

// xUnit v3 generates an entry point (XunitAutoGeneratedEntryPoint) for test execution.
// When running via 'dotnet test' or VSTest, args include '--server' or '--internal-msbuild-node'.
// When running via 'dotnet run' without args, xUnit's in-process runner should execute.
// Only start the web server when explicitly requested with --urls (used by ParityServerAssemblyFixture).

var isTestExecution = args.Any(arg => arg == "--server" || arg == "--internal-msbuild-node");
var isWebServer = args.Any(arg => arg.StartsWith("--urls", StringComparison.OrdinalIgnoreCase));

if (isTestExecution)
{
    // Delegate to xUnit's test platform for VSTest/dotnet test
    var result = Xunit.MicrosoftTestingPlatform.TestPlatformTestFramework
        .RunAsync(args, Blazix.BaseUI.Parity.Tests.SelfRegisteredExtensions.AddSelfRegisteredExtensions)
        .GetAwaiter().GetResult();
    return result;
}

if (!isWebServer)
{
    // Running via 'dotnet run' without --urls: use xUnit's in-process console runner
    var result = Xunit.Runner.InProc.SystemConsole.ConsoleRunner.Run(args).GetAwaiter().GetResult();
    return result;
}

// Web server mode: start the Blazor application (used by ParityServerAssemblyFixture via 'dotnet run --urls ...')
// Note: This path doesn't return a value because app.Run() blocks until shutdown
var builder = WebApplication.CreateBuilder(args);

builder.Logging.ClearProviders();
builder.Logging.AddConsole();
builder.Logging.AddDebug();

// Add services to the container.
// AvatarFallback has an [Inject] TimeProvider property, so Blazor property injection throws at
// component instantiation unless TimeProvider is registered - regardless of whether Delay is set.
builder.Services.AddSingleton(TimeProvider.System);

// DetailedErrors keeps the Server leg from reporting only a generic "circuit terminated"
// while the WASM leg prints the real exception - an asymmetry that makes a harness defect
// look like a component discrepancy. This host is never deployed.
builder.Services.AddRazorComponents(options => options.DetailedErrors = true)
    .AddInteractiveServerComponents()
    .AddInteractiveWebAssemblyComponents();

var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseWebAssemblyDebugging();
}
else
{
    app.UseExceptionHandler("/Error", createScopeForErrors: true);
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();
}
app.UseAntiforgery();

app.MapStaticAssets();

// Serve the Vite-built base-ui demo bundle from the same origin, under /react.
var reactDist = Path.Combine(AppContext.BaseDirectory, "react-dist");
if (Directory.Exists(reactDist))
{
    app.UseFileServer(new FileServerOptions
    {
        FileProvider = new PhysicalFileProvider(reactDist),
        RequestPath = "/react",
        EnableDefaultFiles = true
    });
}

app.MapRazorComponents<App>()
    .AddInteractiveServerRenderMode()
    .AddInteractiveWebAssemblyRenderMode()
    .AddAdditionalAssemblies(typeof(Blazix.BaseUI.Parity.Tests.Client._Imports).Assembly);

app.Run();

return 0;

// Required for WebApplicationFactory<Program>
public partial class Program { }
